# Generated by Django 5.1.6 on 2025-03-05 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('gender', models.IntegerField(choices=[(1, '男'), (0, '女')], default=0)),
                ('password', models.CharField(max_length=255)),
                ('description', models.TextField(null=True, verbose_name='简介')),
                ('avatar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.file', verbose_name='用户头像')),
            ],
        ),
    ]
