# Generated by Django 5.1.6 on 2025-03-05 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, null=True, unique=True)),
                ('originalname', models.CharField(max_length=255, null=True)),
                ('dest', models.CharField(max_length=125, null=True)),
                ('filename', models.CharField(max_length=125)),
                ('size', models.IntegerField(max_length=125)),
                ('createTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('updateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
