# Generated by Django 5.1.6 on 2025-03-05 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='file',
            table='file',
        ),
    ]
