# Generated by Django 5.1.6 on 2025-03-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cinema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225, verbose_name="影院名称")),
                (
                    "alias",
                    models.CharField(max_length=500, null=True, verbose_name="别名"),
                ),
                ("address", models.CharField(max_length=500, verbose_name="影院地址")),
                ("createTime", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cinema",
            },
        ),
    ]
