# Generated by Django 5.1.6 on 2025-03-20 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
        ("file", "0004_alter_file_size"),
        ("user", "0003_alter_user_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="CinemaTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                ("createTime", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cinema_tag",
            },
        ),
        migrations.AddField(
            model_name="cinema",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="user.user"
            ),
        ),
        migrations.CreateModel(
            name="CinemaFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225, verbose_name="名称")),
                (
                    "old_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="原价"
                    ),
                ),
                (
                    "new_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="现价"
                    ),
                ),
                ("args", models.CharField(max_length=500, verbose_name="参数")),
                ("is_delete", models.IntegerField(default=0, verbose_name="是否删除")),
                (
                    "cinema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cinema.cinema"
                    ),
                ),
                (
                    "cover",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="file.file",
                    ),
                ),
            ],
            options={
                "db_table": "cinema_food",
            },
        ),
        migrations.CreateModel(
            name="CinemaFoodOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(max_length=6)),
                ("createTime", models.DateTimeField(auto_now=True)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cinema.cinemafood",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
            options={
                "db_table": "cinema_food_order",
            },
        ),
        migrations.CreateModel(
            name="CinemaHall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225, verbose_name="影厅名称")),
                ("language", models.CharField(max_length=125, verbose_name="影厅语种")),
                ("seat", models.CharField(max_length=225, verbose_name="座位图")),
                (
                    "cinema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cinema.cinema"
                    ),
                ),
            ],
            options={
                "db_table": "cinema_hall",
            },
        ),
        migrations.CreateModel(
            name="CinemaRelateTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createTime", models.DateTimeField(auto_now=True)),
                (
                    "cinema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cinema.cinema"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cinema.cinematag",
                    ),
                ),
            ],
            options={
                "db_table": "cinema_relate_tag",
            },
        ),
    ]
