# Generated by Django 5.1.6 on 2025-03-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_cinematag_cinema_user_cinemafood_cinemafoodorder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cinema",
            name="tag",
            field=models.ManyToManyField(
                through="cinema.CinemaRelateTag", to="cinema.cinematag"
            ),
        ),
    ]
