# Generated by Django 5.1.6 on 2025-03-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_cinema_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinemafoodorder",
            name="count",
            field=models.IntegerField(),
        ),
    ]
