# Generated by Django 5.1.6 on 2025-03-27 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("file", "0004_alter_file_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=125, verbose_name="演员名称")),
                ("description", models.TextField(null=True, verbose_name="简介")),
                ("birthday", models.DateTimeField(null=True)),
                (
                    "birthplace",
                    models.CharField(max_length=125, null=True, verbose_name="出生地"),
                ),
                (
                    "identity",
                    models.CharField(max_length=125, null=True, verbose_name="身份"),
                ),
                (
                    "gender",
                    models.IntegerField(
                        choices=[(0, "男"), (1, "女")], default=0, verbose_name="性别"
                    ),
                ),
                (
                    "nationality",
                    models.CharField(max_length=125, null=True, verbose_name="国籍"),
                ),
                (
                    "people",
                    models.CharField(max_length=125, null=True, verbose_name="民族"),
                ),
                (
                    "height",
                    models.CharField(max_length=125, null=True, verbose_name="身高"),
                ),
                (
                    "constellation",
                    models.CharField(max_length=125, null=True, verbose_name="星座"),
                ),
                (
                    "school",
                    models.CharField(
                        max_length=125, null=True, verbose_name="毕业学校"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        max_length=125, null=True, verbose_name="经济公司"
                    ),
                ),
                (
                    "avatar",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="file.file",
                    ),
                ),
            ],
            options={
                "db_table": "actor",
            },
        ),
        migrations.CreateModel(
            name="ActorDeductive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.DateField()),
                ("description", models.TextField(verbose_name="演绎经历描述")),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="actor.actor"
                    ),
                ),
            ],
            options={
                "db_table": "actor_deductive",
            },
        ),
        migrations.CreateModel(
            name="ActorMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="actor.actor"
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="file.file"
                    ),
                ),
            ],
            options={
                "db_table": "actor_media",
            },
        ),
    ]
