# Generated by Django 5.1.6 on 2025-02-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122, verbose_name='姓名')),
                ('age', models.IntegerField(null=True, verbose_name='年')),
            ],
        ),
        migrations.CreateModel(
            name='Girls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122, verbose_name='姓名')),
                ('relation', models.ManyToManyField(to='setting.boy', verbose_name='男女关系')),
            ],
        ),
    ]
