# Generated by Django 5.1.6 on 2025-02-27 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='角色名称')),
                ('create_time', models.DateField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='理想', max_length=84, unique=True, verbose_name='名称')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=111, verbose_name='性别')),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别哈')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('count', models.BigIntegerField(default=1, verbose_name='数量')),
                ('create_time', models.DateField(auto_now=True, verbose_name='日期')),
                ('is_login', models.BooleanField(default=False, verbose_name='是否登录')),
                ('money', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='金额')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='用户名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('description', models.TextField(verbose_name='描述')),
                ('create_time', models.DateField(auto_now=True, verbose_name='创建时间')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.role', verbose_name='角色')),
            ],
        ),
    ]
