# Generated by Django 5.1.6 on 2025-02-28 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_role_setting_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
