# Generated by Django 5.1.6 on 2025-02-28 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_remove_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
