# Generated by Django 5.1.6 on 2025-02-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=128, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], default=2, verbose_name='性别'),
        ),
    ]
