# Generated by Django 5.1.6 on 2025-03-08 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
    ]
