# Generated by Django 5.1.6 on 2025-03-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_rolemenu_menu_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemenu',
            name='half',
            field=models.IntegerField(default=0),
        ),
    ]
