# Generated by Django 5.1.6 on 2025-03-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_rolemenu_half'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
