# Generated by Django 5.1.6 on 2025-03-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
        migrations.AlterModelTable(
            name='userrole',
            table='user_role',
        ),
    ]
