# Generated by Django 5.1.6 on 2025-03-25 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("file", "0004_alter_file_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilmCate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                ("createTime", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "film_cate",
            },
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=225, unique=True, verbose_name="名称"),
                ),
                ("foreign_name", models.CharField(max_length=225, null=True)),
                ("alias", models.CharField(max_length=225, null=True)),
                ("dt", models.IntegerField(default=0)),
                ("language", models.CharField(max_length=125, null=True)),
                ("description", models.TextField(null=True)),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="评分"
                    ),
                ),
                ("release_time", models.DateTimeField(verbose_name="上映时间")),
                (
                    "cover",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="file.file",
                        verbose_name="封面",
                    ),
                ),
            ],
            options={
                "db_table": "film",
            },
        ),
        migrations.CreateModel(
            name="FileRelateCate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="film.film"
                    ),
                ),
                (
                    "cate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="film.filmcate"
                    ),
                ),
            ],
            options={
                "db_table": "film_relate_cate",
            },
        ),
    ]
