# Generated by Django 5.1.6 on 2025-03-26 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file", "0004_alter_file_size"),
        ("film", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="cover",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="film_cover",
                to="file.file",
                verbose_name="封面",
            ),
        ),
        migrations.CreateModel(
            name="FilmVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=125, verbose_name="视频分类或简介"),
                ),
                (
                    "minitype",
                    models.CharField(
                        max_length=100, verbose_name="文件类型图片或者视频"
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="file.file"
                    ),
                ),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="film.film"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="film",
            name="media",
            field=models.ManyToManyField(
                related_name="film_media",
                through="film.FilmVideo",
                to="file.file",
                verbose_name="媒体文件",
            ),
        ),
    ]
