# Generated by Django 5.1.6 on 2025-03-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("film", "0003_alter_filmvideo_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmcate",
            name="meta",
            field=models.CharField(default="1", max_length=100),
        ),
    ]
