# Generated by Django 5.1.6 on 2025-03-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("film", "0004_filmcate_meta"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FileRelateCate",
            new_name="FilmRelateCate",
        ),
    ]
