# Generated by Django 5.1.6 on 2025-03-26 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("film", "0005_rename_filerelatecate_filmrelatecate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmrelatecate",
            name="cate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="app",
                to="film.filmcate",
            ),
        ),
    ]
