# Generated by Django 5.1.6 on 2025-03-27 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("film", "0006_alter_filmrelatecate_cate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmrelatecate",
            name="cate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="film.filmcate"
            ),
        ),
    ]
